name: Create Theme Release

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '[release]')

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get Version from style.css
        id: get_version
        run: echo "VERSION=$(grep -i '^Version:' style.css | cut -d':' -f2 | tr -d ' ')" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.VERSION }}
          release_name: Release v${{ env.VERSION }}
          body: |
            Автоматический релиз версии ${{ env.VERSION }}
            Изменения в этом коммите: ${{ github.event.head_commit.message }}
          draft: false
          prerelease: false 